"use client";

import { useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Shield } from "lucide-react";

const LAST_UPDATED = "29 September 2026";

const definitionItems = [
  { term: "Account", text: "A unique account created for You to access our Service or parts of our Service." },
  {
    term: "Company",
    text: 'Referred to as either "the Company", "We", "Us" or "Our" in this Agreement. Refers to Shelter Incorporated, Shelter House, 95 Fife Avenue, Harare, Zimbabwe.',
  },
  { term: "Country", text: "Zimbabwe" },
  {
    term: "Device",
    text: "Any device that can access the Service such as a computer, a cell phone or a digital tablet.",
  },
  {
    term: "Personal Data",
    text: "Any information that relates to an identified or identifiable individual.",
  },
  {
    term: "Usage Data",
    text: "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
  },
  {
    term: "Website",
    text: "Shelter Incorporated website, accessible from https://www.shelter.co.zw",
  },
  {
    term: "You",
    text: "The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
  },
];

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h3 className="mb-3 text-base font-bold text-slate-900 sm:text-lg">{title}</h3>
      <div className="space-y-3 text-sm leading-6 text-slate-600 sm:text-[15px] sm:leading-7">
        {children}
      </div>
    </section>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="list-disc space-y-1.5 pl-5 marker:text-[#2652a2]">
      {items.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  );
}

function PrivacyPolicyContent() {
  return (
    <>
      <div className="rounded-2xl border border-[#2652a2]/15 bg-[#f8fbff] p-4 text-sm leading-6 text-slate-700 sm:p-5 sm:text-[15px] sm:leading-7">
        <p>
          This Privacy Policy describes Our policies and procedures on the collection, use, storage,
          sharing, protection and disclosure of Your Personal Information when You use our Service and
          tells You about Your privacy rights and how the law protects You. We use Your Personal data
          to provide and improve the Service. By using the Service, You agree to the collection and
          use of information in accordance with this Privacy Policy.
        </p>
      </div>

      <div className="space-y-8">
        <Section title="1. Introduction">
          <p>
            Shelter Incorporated is committed to protecting your privacy and ensuring that your
            personal information is processed responsibly, lawfully, and securely.
          </p>
          <p>
            This Privacy Policy explains how we collect, use, disclose, store, and protect your
            personal information in accordance with the Cyber and Data Protection Act [Chapter 12:07]
            of Zimbabwe and other applicable laws.
          </p>
          <p>
            By providing your personal information to us or using our services, you acknowledge that
            you have read and understood this Privacy Policy.
          </p>
        </Section>

        <Section title="2. Who We Are">
          <p>
            Shelter Incorporated is a land development company engaged in land acquisition, servicing,
            property sales, housing development, property management and related services.
          </p>
        </Section>

        <Section title="3. Interpretation and Definitions">
          <div>
            <h4 className="mb-2 font-semibold text-slate-800">Interpretation</h4>
            <p>
              The words whose initial letters are capitalized have meanings defined under the
              following conditions. The following definitions shall have the same meaning regardless
              of whether they appear in singular or in plural.
            </p>
          </div>
          <div>
            <h4 className="mb-2 font-semibold text-slate-800">Definitions</h4>
            <p className="mb-3">For the purposes of this Privacy Policy:</p>
            <dl className="space-y-3">
              {definitionItems.map(({ term, text }) => (
                <div key={term} className="rounded-xl border border-slate-200 bg-slate-50 p-3 sm:p-4">
                  <dt className="text-sm font-semibold text-[#2652a2]">{term}</dt>
                  <dd className="mt-1 text-sm text-slate-600">{text}</dd>
                </div>
              ))}
            </dl>
          </div>
        </Section>

        <Section title="4. Personal Information We Collect">
          <p>Depending on your relationship with us, we may collect:</p>
          <div className="space-y-4">
            <div>
              <h4 className="mb-1.5 font-semibold text-slate-800">Identification Information</h4>
              <BulletList items={["Full names", "National Identity Number", "Passport Number", "Driver's Licence", "Date of birth"]} />
            </div>
            <div>
              <h4 className="mb-1.5 font-semibold text-slate-800">Contact Information</h4>
              <BulletList items={["Residential address", "Postal address", "Telephone numbers", "Email address"]} />
            </div>
            <div>
              <h4 className="mb-1.5 font-semibold text-slate-800">Property Information</h4>
              <BulletList items={["Stand allocation details", "Property ownership records", "Survey information", "Sale agreements", "Transfer documentation"]} />
            </div>
            <div>
              <h4 className="mb-1.5 font-semibold text-slate-800">Financial Information</h4>
              <BulletList items={["Bank account details", "Payment records", "Mortgage information", "Tax details"]} />
            </div>
            <div>
              <h4 className="mb-1.5 font-semibold text-slate-800">Employment Information</h4>
              <p className="mb-1.5">For employees and job applicants:</p>
              <BulletList items={["Curriculum Vitae", "Educational qualifications", "Employment history", "Payroll details", "Pension information", "Medical aid information"]} />
            </div>
            <div>
              <h4 className="mb-1.5 font-semibold text-slate-800">Supplier Information</h4>
              <BulletList items={["Company registration documents", "Tax clearance certificates", "Banking details", "Contact persons"]} />
            </div>
            <div>
              <h4 className="mb-1.5 font-semibold text-slate-800">Technical Information</h4>
              <p className="mb-1.5">When you visit our website, we may collect:</p>
              <BulletList items={["IP address", "Browser type", "Device information", "Website usage information"]} />
            </div>
          </div>
        </Section>

        <Section title="5. How We Collect Information">
          <p>We collect personal information through:</p>
          <BulletList items={["Property application forms", "Sale agreements", "Customer registration", "Website enquiries", "Email correspondence", "Telephone conversations", "Employment applications", "Supplier registration", "Public records where legally permitted", "Regulatory authorities"]} />
        </Section>

        <Section title="6. Why We Collect Your Information">
          <p>We process your information to:</p>
          <BulletList items={["Process property applications", "Allocate residential or commercial stands", "Prepare sale agreements", "Facilitate property transfers", "Process payments", "Manage customer accounts", "Communicate with you", "Respond to enquiries", "Manage employment relationships", "Administer supplier contracts", "Comply with legal and regulatory obligations", "Prevent fraud", "Resolve disputes", "Improve our services"]} />
        </Section>

        <Section title="7. Legal Basis for Processing">
          <p>We process personal information where:</p>
          <BulletList items={["You have given consent.", "Processing is necessary to perform a contract.", "Processing is required by law.", "Processing protects legitimate business interests.", "Processing is necessary to protect vital interests."]} />
        </Section>

        <Section title="8. Disclosure of Personal Information">
          <p>Your information may be shared with:</p>
          <BulletList items={["Government ministries and departments", "Local authorities", "Financial institutions", "Legal practitioners", "External auditors", "Surveyors", "Estate agents acting on our behalf", "Contractors performing services", "Information technology service providers", "Regulatory authorities", "Courts where required by law"]} />
          <p>We do not sell your personal information to third parties.</p>
        </Section>

        <Section title="9. Data Security">
          <p>We implement appropriate administrative, physical, and technical measures to protect personal information, including:</p>
          <BulletList items={["Password-protected systems", "Encryption where appropriate", "Firewalls and antivirus software", "Secure servers", "Access controls based on business need", "Locked filing cabinets", "Visitor access controls", "Employee confidentiality obligations", "Regular system monitoring"]} />
        </Section>

        <Section title="10. Data Retention">
          <p>We retain personal information only for as long as necessary to:</p>
          <BulletList items={["Fulfil contractual obligations", "Comply with legal requirements", "Resolve disputes", "Maintain business records", "Enforce agreements"]} />
          <p>When information is no longer required, it will be securely deleted, destroyed, or anonymised.</p>
        </Section>

        <Section title="11. Your Rights">
          <p>Subject to applicable law, you may have the right to:</p>
          <BulletList items={["Request access to your personal information.", "Request correction of inaccurate or incomplete information.", "Request deletion of personal information where legally permissible.", "Withdraw consent where processing is based on consent.", "Object to certain processing activities.", "Request restriction of processing in appropriate circumstances.", "Lodge a complaint regarding the handling of your personal information."]} />
        </Section>

        <Section title="12. Marketing Communications">
          <p>Through your consent, we may send you information regarding:</p>
          <BulletList items={["New property developments", "Residential stands", "Commercial property opportunities", "Promotions", "Company announcements"]} />
          <p>You may opt out of marketing communications at any time by contacting us or using the unsubscribe option where available.</p>
        </Section>

        <Section title="13. Children's Personal Information">
          <p>We do not knowingly collect personal information from children except where required by law or where consent has been provided by a parent or legal guardian.</p>
        </Section>

        <Section title="14. Confidentiality">
          <p>All employees, consultants, contractors, and service providers are required to maintain the confidentiality of personal information and may only process such information for authorised purposes.</p>
        </Section>

        <Section title="15. Data Breach Notification">
          <p>
            In the event of a data breach, we are legally obliged to notify the Data Protection
            Authority (POTRAZ) within twenty four (24) hours of becoming aware of the incident. Where
            the breach is likely to result in a high risk to your rights and freedoms, we will also
            inform affected data subjects within seventy two (72) hours.
          </p>
        </Section>

        <Section title="16. Changes to this Privacy Policy">
          <p>We may amend this Privacy Policy from time to time to reflect changes in legal requirements, business operations, or technology. The latest version will be made available through our offices and, where applicable, on our website.</p>
        </Section>

        <Section title="17. Complaints">
          <p>
            If you believe that your personal information has been handled improperly, you may submit a
            complaint to the Organisation using the contact details above. We will investigate your
            complaint and respond within 30 days. If you remain dissatisfied, you may seek recourse
            through the appropriate regulatory or legal channels available under Zimbabwean law.
          </p>
        </Section>

        <Section title="18. Contact Us">
          <p>If you have any questions about this Privacy Policy or wish to exercise your privacy rights, please contact:</p>
          <div className="rounded-2xl border border-[#2652a2]/20 bg-[#2652a2]/5 p-4 text-slate-700 sm:p-5">
            <p><span className="font-semibold text-slate-900">Physical Address:</span> Shelter House, 95 Fife Avenue, Harare</p>
            <p className="mt-2"><span className="font-semibold text-slate-900">Postal Address:</span> Shelter House, 95 Fife Avenue, Harare</p>
            <p className="mt-2">
              <span className="font-semibold text-slate-900">Telephone:</span>{" "}
              <a href="tel:+263242774455" className="text-[#2652a2] hover:underline">+263 242 774 455</a> /{" "}
              <a href="tel:+263242748121" className="text-[#2652a2] hover:underline">748 121</a>
            </p>
            <p className="mt-2">
              <span className="font-semibold text-slate-900">Email:</span>{" "}
              <a href="mailto:dpo@shelter.co.zw" className="text-[#2652a2] hover:underline">sales@shelter.co.zw</a>
            </p>
          </div>
        </Section>
      </div>
    </>
  );
}

interface PrivacyPolicyModalProps {
  open: boolean;
  onClose: () => void;
}

export default function PrivacyPolicyModal({ open, onClose }: PrivacyPolicyModalProps) {
  useEffect(() => {
    if (!open) return;

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };

    document.body.style.overflow = "hidden";
    window.addEventListener("keydown", handleKeyDown);

    return () => {
      document.body.style.overflow = "";
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [open, onClose]);

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[60] flex items-end justify-center bg-black/65 p-0 sm:items-center sm:p-4"
          onClick={onClose}
          role="dialog"
          aria-modal="true"
          aria-labelledby="privacy-policy-title"
        >
          <motion.div
            initial={{ opacity: 0, y: 40, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 24, scale: 0.98 }}
            transition={{ type: "spring", damping: 28, stiffness: 320 }}
            className="relative flex max-h-[92vh] w-full max-w-3xl flex-col overflow-hidden rounded-t-3xl border border-slate-200 bg-white shadow-2xl sm:rounded-3xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div
              className="absolute inset-x-0 top-0 h-1"
              style={{ background: "linear-gradient(90deg, #2652a2, #00aeed, #29ddda)" }}
            />

            <div
              className="sticky top-0 z-10 border-b border-slate-200 px-5 py-5 sm:px-6"
              style={{
                background:
                  "linear-gradient(135deg, rgba(38, 82, 162, 0.06), rgba(0, 174, 237, 0.04), rgba(255,255,255,0.98))",
              }}
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-start gap-3">
                  <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#2652a2]/10 text-[#2652a2]">
                    <Shield className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#2652a2]">
                      Legal
                    </p>
                    <h2 id="privacy-policy-title" className="text-xl font-bold text-slate-900 sm:text-2xl">
                      Privacy Policy
                    </h2>
                    <p className="mt-0.5 text-sm font-medium text-slate-600">Shelter Incorporated</p>
                    <p className="mt-1 text-xs text-slate-500">Last updated: {LAST_UPDATED}</p>
                  </div>
                </div>
                <button
                  type="button"
                  onClick={onClose}
                  className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-100 text-slate-700 transition hover:bg-slate-200"
                  aria-label="Close privacy policy"
                >
                  <X className="h-5 w-5" />
                </button>
              </div>
            </div>

            <div className="flex-1 space-y-8 overflow-y-auto px-5 py-6 sm:px-6 sm:py-8">
              <PrivacyPolicyContent />
            </div>

            <div className="sticky bottom-0 border-t border-slate-200 bg-white/95 px-5 py-4 backdrop-blur sm:px-6">
              <button
                type="button"
                onClick={onClose}
                className="w-full rounded-2xl px-6 py-3 text-sm font-semibold text-white transition hover:shadow-lg sm:w-auto"
                style={{ background: "linear-gradient(135deg, #2652a2, #00aeed, #29ddda)" }}
              >
                Close
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
